// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "77d36fbb-bad1-40e2-a6d9-73d3a2b18db7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1556184254);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1556184374);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1556188047);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1556184014);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1556183894);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1556184134);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1556096832);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1556184494);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1552473798);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c6e44dfa-2b00-4e5f-8b14-3e703456d919}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1552415400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1557148779190");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1557150606190");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1556185085116");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1556188685116");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190410105841");
user_pref("browser.slowStartup.averageTime", 2770);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190410105841");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1552473803469");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolbox.footer.height", 383);
user_pref("devtools.toolbox.zoomValue", "1.7");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "36eecaa367c74b128dc6350493efc143");
user_pref("extensions.blocklist.lastModified", "Wed, 24 Apr 2019 13:21:59 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1556184257);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190410105841");
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{2241200b-e634-4047-82dd-509fe25ae9a4}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"7af2b5f7-dd0f-4549-b3fa-0ce7c30f61b5\",\"screenshots@mozilla.org\":\"e2bc2008-a118-406d-82ef-a4737258b5c7\",\"webcompat-reporter@mozilla.org\":\"83b8819d-33f7-40f6-91d1-3382a5ef93a3\",\"webcompat@mozilla.org\":\"aed04368-500f-4686-87d6-a3d29db4c3f8\",\"fxmonitor@mozilla.org\":\"1ff5f773-0a87-420d-8713-f9ac3a64bf00\"}");
user_pref("idle.lastDailyNotification", 1556184203);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1556096478);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190410105841");
user_pref("media.gmp-manager.lastCheck", 1556184045);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1556097041);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a77dc637-8de1-4f84-8208-13f70c953115");
user_pref("security.sandbox.plugin.tempDirSuffix", "7a9fae17-24cb-4244-bfa9-407cdef22944");
user_pref("services.blocklist.addons.checked", 1556184074);
user_pref("services.blocklist.gfx.checked", 1556184074);
user_pref("services.blocklist.onecrl.checked", 1556184074);
user_pref("services.blocklist.pinning.checked", 1556184074);
user_pref("services.blocklist.plugins.checked", 1556184074);
user_pref("services.settings.clock_skew_seconds", -69);
user_pref("services.settings.last_update_seconds", 1556184203);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1556184074);
user_pref("services.settings.main.language-dictionaries.last_check", 1556184074);
user_pref("services.settings.main.onboarding.last_check", 1556184074);
user_pref("services.settings.main.sites-classification.last_check", 1556184074);
user_pref("services.settings.main.tippytop.last_check", 1556184074);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1556097041);
user_pref("toolkit.startup.last_success", 1557148767);
user_pref("toolkit.telemetry.cachedClientID", "4a03ed8c-aeda-472f-9940-47eb3dc3a408");
user_pref("toolkit.telemetry.previousBuildID", "20190410105841");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
